# Use an official Node.js runtime as the base image
FROM node:18.16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json before other files
# Utilize Docker cache to save re-installing dependencies if unchanged
COPY ./frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY . .

# Make port 3000 available outside this container
EXPOSE 3000

# Run the app when the container launches
CMD ["npm", "start"]
