volumes:
  mongodb_data:

services:
  fastapi:
    environment:
      CORS_HOST: ${CORS_HOST}
      MONGO_URL: ${MONGO_URL}
      SIGNING_KEY: ${SIGNING_KEY}
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: myfrontend:dev
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      VITE_API_HOST: http://fastapi:8000
      VITE_SIGNING_KEY: ${VITE_SIGNING_KEY}

  mongo:
    image: mongo:latest
    volumes:
      - ./setup/mongodb:/docker-entrypoint-initdb.d
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
